# Generated by Django 5.1 on 2024-08-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=50)),
                ('asignatura', models.CharField(max_length=100)),
                ('modulos', models.IntegerField()),
                ('docente', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='nombre',
            new_name='edificio',
        ),
        migrations.AddField(
            model_name='sala',
            name='codigo_sala',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='nombre_sala',
            field=models.CharField(default='Sala Desconocida', max_length=100),
            preserve_default=False,
        ),
    ]
