# Generated by Django 5.1 on 2024-09-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sala_codigo_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulos', models.IntegerField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examen')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sala')),
            ],
        ),
    ]
