# Generated by Django 5.1 on 2024-09-03 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
